contact1 = Contact.create({name: "Bill", address: "71 Hickory Lane"})
contact2 = Contact.create({name: "Bob", address: "12 Edward Ave"}) 
contact3 = Contact.create({name: "Bart", address: "OnTheStreet"})
contact4 = Contact.create({name: "Barry", address: "Address 123"})
contact5 = Contact.create({name: "Beth", address: "Under a bridge"})
contact6 = Contact.create({name: "Carry", address: "In a hut"}) 
contact7 = Contact.create({name: "Cat", address: "321 Sesame Street"})
contact8 = Contact.create({name: "Carl", address: "Address 123"})
contact9 = Contact.create({name: "Casey", address: "1235 Washington RD"})
contact10 = Contact.create({name: "Candy", address: "Address 123"})

contact1.phonenumbers.create({phonenumber: "555-555-5555"})
contact2.phonenumbers.create({phonenumber: "555-555-5555"})
contact3.phonenumbers.create({phonenumber: "555-555-5555"})
contact4.phonenumbers.create({phonenumber: "555-555-5555"})
contact5.phonenumbers.create({phonenumber: "555-555-5555"})
contact6.phonenumbers.create({phonenumber: "555-555-5555"})
contact7.phonenumbers.create({phonenumber: "555-555-5555"})
contact8.phonenumbers.create({phonenumber: "555-555-5555"})
contact9.phonenumbers.create({phonenumber: "555-555-5555"})
contact10.phonenumbers.create({phonenumber: "555-555-5555"})

contact1.emails.create({email: "email@example.com"})
contact2.emails.create({email: "email@example.com"})
contact3.emails.create({email: "email@example.com"})
contact4.emails.create({email: "email@example.com"})
contact5.emails.create({email: "email@example.com"})
contact6.emails.create({email: "email@example.com"})
contact7.emails.create({email: "email@example.com"})
contact8.emails.create({email: "email@example.com"})
contact9.emails.create({email: "email@example.com"})
contact10.emails.create({email: "email@example.com"})



